# .travis.yml

language: minimal

services:
  - docker

env:
  global:
    - IMAGE_TAG=v1 # Update the tag as needed for each build

before_script:
  # Build Docker images for each service
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy

  # Tag images with DockerHub registry
  - docker tag udagram-api-feed $DOCKER_USERNAME/udagram-api-feed:$IMAGE_TAG
  - docker tag udagram-api-user $DOCKER_USERNAME/udagram-api-user:$IMAGE_TAG
  - docker tag udagram-frontend $DOCKER_USERNAME/udagram-frontend:$IMAGE_TAG
  - docker tag udagram-reverseproxy $DOCKER_USERNAME/udagram-reverseproxy:$IMAGE_TAG

script:
  # Push images to DockerHub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $DOCKER_USERNAME/udagram-api-feed:$IMAGE_TAG
  - docker push $DOCKER_USERNAME/udagram-api-user:$IMAGE_TAG
  - docker push $DOCKER_USERNAME/udagram-frontend:$IMAGE_TAG
  - docker push $DOCKER_USERNAME/udagram-reverseproxy:$IMAGE_TAG