apiVersion: v1
kind: Service
metadata:
  labels:
    app: udagram-reverseproxy
  name: udagram-reverseproxy-svc
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 8080
  selector:
    app: udagram-reverseproxy
  type: LoadBalancer